[server]
headless = true

[theme]
base = "light"
primaryColor = "#cd2128"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f5f6f8"
textColor = "#111318"

[browser]
gatherUsageStats = false
